SELECT
    B.CONTEST_ID,
    A.HACKER_ID,
    A.NAME,
    SUM(B.TOTAL_SUBMISSIONS),
    SUM(B.TOTAL_ACCEPTED_SUBMISSIONS),
    SUM(B.TOTAL_VIEWS),
    SUM(B.TOTAL_UNIQUE_VIEWS)
FROM
    CONTESTS AS A
LEFT JOIN
(SELECT
    (SELECT CONTEST_ID FROM COLLEGES WHERE CHALLENGES.COLLEGE_ID = COLLEGES.COLLEGE_ID) AS CONTEST_ID,
    COLLEGE_ID,
    CHALLENGE_ID,
    (SELECT SUM(TOTAL_SUBMISSIONS) FROM SUBMISSION_STATS WHERE CHALLENGES.CHALLENGE_ID = SUBMISSION_STATS.CHALLENGE_ID) AS TOTAL_SUBMISSIONS,
      (SELECT SUM(TOTAL_ACCEPTED_SUBMISSIONS) FROM SUBMISSION_STATS WHERE CHALLENGES.CHALLENGE_ID = SUBMISSION_STATS.CHALLENGE_ID) AS TOTAL_ACCEPTED_SUBMISSIONS,
    (SELECT SUM(TOTAL_VIEWS) FROM VIEW_STATS WHERE CHALLENGES.CHALLENGE_ID = VIEW_STATS.CHALLENGE_ID) AS TOTAL_VIEWS,
    (SELECT SUM(TOTAL_UNIQUE_VIEWS) FROM VIEW_STATS WHERE CHALLENGES.CHALLENGE_ID = VIEW_STATS.CHALLENGE_ID) AS TOTAL_UNIQUE_VIEWS
FROM
    CHALLENGES) AS B
ON
    A.CONTEST_ID = B.CONTEST_ID
WHERE
    B.CONTEST_ID IS NOT NULL
GROUP BY
    B.CONTEST_ID, A.HACKER_ID, A.NAME