SELECT
    NAME
FROM
(SELECT
    S.ID,
    S.NAME,
    (SELECT P.SALARY FROM PACKAGES AS P WHERE S.ID = P.ID) AS SALARY,
    F.FRIEND_ID,
    (SELECT P.SALARY FROM PACKAGES AS P WHERE F.FRIEND_ID = P.ID) AS FRIEND_SALARY
FROM
    STUDENTS AS S LEFT JOIN FRIENDS AS F
ON
    S.ID = F.ID) AS A
WHERE
    SALARY < FRIEND_SALARY
ORDER BY
    FRIEND_SALARY