SELECT DISTINCT
    X1,
    Y1
FROM
(SELECT
    A.X AS X1,
    A.Y AS Y1,
    B.X AS X2,
    B.Y AS Y2,
    A.DUP_COUNT,
    CASE WHEN A.X = B.Y AND A.Y = B.X THEN 1 ELSE 0 END AS IS_SYMMETRIC
FROM
(SELECT DISTINCT
    X,
    Y,
    COUNT(X) OVER(PARTITION BY X, Y ORDER BY X) AS DUP_COUNT
FROM
    FUNCTIONS) AS A FULL JOIN FUNCTIONS AS B
ON
    1 = 1 AND ((A.X < B.X AND A.Y != B.Y) OR A.DUP_COUNT = 2)) AS C
WHERE
    IS_SYMMETRIC = 1
ORDER BY
    X1