SELECT
    X.COMPANY_CODE,
    X.FOUNDER,
    COUNT(DISTINCT X.LEAD_MANAGER_CODE),
    COUNT(DISTINCT X.SENIOR_MANAGER_CODE),
    COUNT(DISTINCT X.MANAGER_CODE),
    COUNT(DISTINCT X.EMPLOYEE_CODE)
FROM
(SELECT DISTINCT
    G.*,
    H.EMPLOYEE_CODE
FROM
(SELECT DISTINCT
    E.*,
    F.MANAGER_CODE
FROM
(SELECT DISTINCT
    C.*,
    D.SENIOR_MANAGER_CODE
FROM
(SELECT DISTINCT
    A.COMPANY_CODE,
    A.FOUNDER,
    B.LEAD_MANAGER_CODE
FROM
    COMPANY AS A LEFT JOIN LEAD_MANAGER AS B
ON A.COMPANY_CODE = B.COMPANY_CODE) AS C
LEFT JOIN SENIOR_MANAGER AS D
ON  C.COMPANY_CODE = D.COMPANY_CODE AND 
    C.LEAD_MANAGER_CODE = D.LEAD_MANAGER_CODE) AS E
LEFT JOIN MANAGER AS F
ON  E.COMPANY_CODE = F.COMPANY_CODE AND 
    E.LEAD_MANAGER_CODE = F.LEAD_MANAGER_CODE AND
    E.SENIOR_MANAGER_CODE = F.SENIOR_MANAGER_CODE) AS G
LEFT JOIN EMPLOYEE AS H
ON  G.COMPANY_CODE = H.COMPANY_CODE AND 
    G.LEAD_MANAGER_CODE = H.LEAD_MANAGER_CODE AND
    G.SENIOR_MANAGER_CODE = H.SENIOR_MANAGER_CODE AND
    G.MANAGER_CODE = H.MANAGER_CODE) AS X
GROUP BY
    X.COMPANY_CODE, X.FOUNDER
ORDER BY
    X.COMPANY_CODE