SELECT
    A.SUBMISSION_DATE,
    A.DIST_COUNT,
    F.HACKER_ID,
    F.NAME
FROM
    (SELECT
    SUBMISSION_DATE,
    COUNT(DISTINCT HACKER_ID) AS DIST_COUNT
FROM
(SELECT
    SUBMISSION_DATE,
    HACKER_ID,
    CASE WHEN DAY(SUBMISSION_DATE) = COUNT(HACKER_ID) OVER(PARTITION BY HACKER_ID ORDER BY SUBMISSION_DATE) THEN 1 ELSE 0 END AS FLAG
FROM
    (SELECT DISTINCT
        SUBMISSION_DATE,
        HACKER_ID
    FROM
        SUBMISSIONS
    WHERE  
       SUBMISSION_DATE BETWEEN "2016-03-01" AND "2016-03-15") AS X) AS Y
WHERE
    FLAG = 1
GROUP BY
    SUBMISSION_DATE) AS A
LEFT JOIN
    (SELECT
        E.SUBMISSION_DATE,
        E.HACKER_ID,
        H.NAME
    FROM
        (SELECT
            C.SUBMISSION_DATE,
            MIN(D.HACKER_ID) AS HACKER_ID
        FROM
        (SELECT
            B.SUBMISSION_DATE,
            MAX(B.NUM_SUBS) AS MAX_SUBS
        FROM
            (SELECT
                SUBMISSION_DATE,
                HACKER_ID,
                COUNT(HACKER_ID) AS NUM_SUBS
            FROM
                SUBMISSIONS
            WHERE
               SUBMISSION_DATE BETWEEN "2016-03-01" AND "2016-03-15"
            GROUP BY
                SUBMISSION_DATE, HACKER_ID) AS B
        GROUP BY
            B.SUBMISSION_DATE) AS C
        LEFT JOIN 
        (SELECT
            SUBMISSION_DATE,
            HACKER_ID,
            COUNT(HACKER_ID) AS NUM_SUBS
        FROM
            SUBMISSIONS
        WHERE
           SUBMISSION_DATE BETWEEN "2016-03-01" AND "2016-03-15"
        GROUP BY
            SUBMISSION_DATE, HACKER_ID) AS D
        ON
            C.SUBMISSION_DATE = D.SUBMISSION_DATE AND
            C.MAX_SUBS = D.NUM_SUBS
        GROUP BY
            C.SUBMISSION_DATE) AS E
    LEFT JOIN
        HACKERS AS H
    ON
        E.HACKER_ID = H.HACKER_ID) AS F
ON
  A.SUBMISSION_DATE = F.SUBMISSION_DATE